minimumReleaseAge: 7
minimumReleaseAgeExclude:
  # Renovate security update: react-server-dom-webpack@19.2.5 || 19.2.8
  - react-server-dom-webpack@19.2.5 || 19.2.8
  # Renovate security update: pnpm@11.8.0
  - pnpm@11.8.0
overrides:
  vite: $vite
patchedDependencies:
  waku: patches/waku.patch
saveExact: true
allowBuilds:
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  lefthook: true
