import type { Character, CharacterReleasedLevel } from './types';

export const CHARACTER_RELEASED_LEVELS = [
  'ANIME',
  'COMICS',
  'JUMP_PLUS',
  'YOUNG_JUMP',
] as const satisfies CharacterReleasedLevel[];

export const CHARACTERS: Character[] = [
  { name: '愛城 恋太郎', pronunciation: 'あいじょう れんたろう', birthday: [5, 1], age: 16, releasedLevel: 'ANIME', releaseSeason: 1, type: 'RENTARO' },
  { name: '花園 羽香里', pronunciation: 'はなぞの はかり', birthday: [6, 22], age: 15, releasedLevel: 'ANIME', releaseSeason: 1, type: 'GIRLFRIEND', girlfriendNumber: 1 },
  { name: '院田 唐音', pronunciation: 'いんだ からね', birthday: [9, 9], age: 15, releasedLevel: 'ANIME', releaseSeason: 1, type: 'GIRLFRIEND', girlfriendNumber: 2 },
  { name: '好本 静', pronunciation: 'よしもと しずか', birthday: [11, 1], age: 15, releasedLevel: 'ANIME', releaseSeason: 1, type: 'GIRLFRIEND', girlfriendNumber: 3 },
  { name: '栄逢 凪乃', pronunciation: 'えいあい なの', birthday: [3, 14], age: 15, releasedLevel: 'ANIME', releaseSeason: 1, type: 'GIRLFRIEND', girlfriendNumber: 4 },
  { name: '薬膳 楠莉', pronunciation: 'やくぜん くすり', birthday: [4, 18], age: 18, releasedLevel: 'ANIME', releaseSeason: 1, type: 'GIRLFRIEND', girlfriendNumber: 5 },
  { name: '花園 羽々里', pronunciation: 'はなぞの ははり', birthday: [5, 12], age: 29, releasedLevel: 'ANIME', releaseSeason: 1, type: 'GIRLFRIEND', girlfriendNumber: 6 },
  { name: '原賀 胡桃', pronunciation: 'はらが くるみ', birthday: [9, 3], age: 14, releasedLevel: 'ANIME', releaseSeason: 2, type: 'GIRLFRIEND', girlfriendNumber: 7 },
  { name: '銘戸 芽衣', pronunciation: 'めいど めい', birthday: [5, 10], age: 19, releasedLevel: 'ANIME', releaseSeason: 2, type: 'GIRLFRIEND', girlfriendNumber: 8 },
  { name: '須藤 育', pronunciation: 'すとう いく', birthday: [1, 9], age: 15, releasedLevel: 'ANIME', releaseSeason: 2, type: 'GIRLFRIEND', girlfriendNumber: 9 },
  { name: '美杉 美々美', pronunciation: 'うつくしすぎ みみみ', birthday: [3, 3], age: 16, releasedLevel: 'ANIME', releaseSeason: 2, type: 'GIRLFRIEND', girlfriendNumber: 10 },
  { name: '華暮 愛々', pronunciation: 'かくれ めめ', birthday: [10, 10], age: 15, releasedLevel: 'ANIME', releaseSeason: 2, type: 'GIRLFRIEND', girlfriendNumber: 11 },
  { name: '伊院 知与', pronunciation: 'いいん ちよ', birthday: [10, 1], age: 12, releasedLevel: 'ANIME', releaseSeason: 3, type: 'GIRLFRIEND', girlfriendNumber: 12 },
  { name: 'ナディー', pronunciation: 'なでぃー', birthday: [2, 11], age: 24, releasedLevel: 'ANIME', releaseSeason: 3, type: 'GIRLFRIEND', girlfriendNumber: 13 },
  { name: '優敷 山女', pronunciation: 'やさしき やまめ', birthday: [8, 11], age: 15, releasedLevel: 'COMICS', releaseVolume: 8, type: 'GIRLFRIEND', girlfriendNumber: 14 },
  { name: '茂見 紅葉', pronunciation: 'もみ もみじ', birthday: [4, 8], age: 15, releasedLevel: 'COMICS', releaseVolume: 9, type: 'GIRLFRIEND', girlfriendNumber: 15 },
  { name: '薬膳 ヤク', pronunciation: 'やくぜん やく', birthday: [8, 9], age: 89, releasedLevel: 'COMICS', releaseVolume: 9, type: 'GIRLFRIEND', girlfriendNumber: 16 },
  { name: '土呂瀞 騎士華', pronunciation: 'とろとろ きしか', birthday: [10, 10], age: 17, releasedLevel: 'COMICS', releaseVolume: 10, type: 'GIRLFRIEND', girlfriendNumber: 17 },
  { name: '毛樽井 亜愛子衣', pronunciation: 'けだるい あーしー', birthday: [2, 5], age: 15, releasedLevel: 'COMICS', releaseVolume: 11, type: 'GIRLFRIEND', girlfriendNumber: 18 },
  { name: '中二 詩人', pronunciation: 'なかじ うと', birthday: [5, 16], age: 13, releasedLevel: 'COMICS', releaseVolume: 11, type: 'GIRLFRIEND', girlfriendNumber: 19 },
  { name: '女井戸 妹', pronunciation: 'めいど まい', birthday: [9, 6], age: 15, releasedLevel: 'COMICS', releaseVolume: 12, type: 'GIRLFRIEND', girlfriendNumber: 20 },
  { name: '盆能寺 百八', pronunciation: 'ぼんのうじ ももは', birthday: [10, 8], age: 27, releasedLevel: 'COMICS', releaseVolume: 13, type: 'GIRLFRIEND', girlfriendNumber: 21 },
  { name: '灰尾 凛', pronunciation: 'ばいお りん', birthday: [8, 10], age: 13, releasedLevel: 'COMICS', releaseVolume: 14, type: 'GIRLFRIEND', girlfriendNumber: 22 },
  { name: '一二三 数', pronunciation: 'ひふみ すう', birthday: [1, 23], age: 15, releasedLevel: 'COMICS', releaseVolume: 15, type: 'GIRLFRIEND', girlfriendNumber: 23 },
  { name: '火保 エイラ', pronunciation: 'かほ えいら', birthday: [8, 3], age: 19, releasedLevel: 'COMICS', releaseVolume: 16, type: 'GIRLFRIEND', girlfriendNumber: 24 },
  { name: '猫成 珠', pronunciation: 'ねこなり たま', birthday: [2, 22], age: 21, releasedLevel: 'COMICS', releaseVolume: 17, type: 'GIRLFRIEND', girlfriendNumber: 25 },
  { name: '才奇 姫歌', pronunciation: 'さいき ひめか', birthday: [10, 31], age: 15, releasedLevel: 'COMICS', releaseVolume: 18, type: 'GIRLFRIEND', girlfriendNumber: 26 },
  { name: '出井 祭李', pronunciation: 'でい まつり', birthday: [8, 15], age: 12, releasedLevel: 'COMICS', releaseVolume: 19, type: 'GIRLFRIEND', girlfriendNumber: 27 },
  { name: '宇佐美 椎奈', pronunciation: 'うさみ しいな', birthday: [4, 17], age: 17, releasedLevel: 'COMICS', releaseVolume: 20, type: 'GIRLFRIEND', girlfriendNumber: 28 },
  { name: '雪房田 夢留', pronunciation: 'ぜつぼうだ める', birthday: [11, 30], age: 15, releasedLevel: 'COMICS', releaseVolume: 21, type: 'GIRLFRIEND', girlfriendNumber: 29 },
  { name: '輩 先', pronunciation: 'ともがら さき', birthday: [4, 1, 23, 59, 59], age: 18, releasedLevel: 'COMICS', releaseVolume: 22, type: 'GIRLFRIEND', girlfriendNumber: 30 },
  { name: '根向井 寧夢', pronunciation: 'ねむい ねむ', birthday: [9, 3], age: 13, releasedLevel: 'COMICS', releaseVolume: 23, type: 'GIRLFRIEND', girlfriendNumber: 31 },
  { name: '端須 蓮葉', pronunciation: 'はす はすは', birthday: undefined, age: undefined, releasedLevel: 'JUMP_PLUS', releaseEpisode: 204, type: 'GIRLFRIEND', girlfriendNumber: 32 },
  { name: '守北 季鞠', pronunciation: 'もりきた きまり', birthday: undefined, age: undefined, releasedLevel: 'JUMP_PLUS', releaseEpisode: 213, type: 'GIRLFRIEND', girlfriendNumber: 33 },
  { name: '双天 彗流', pronunciation: 'ふたて える', birthday: undefined, age: undefined, releasedLevel: 'JUMP_PLUS', releaseEpisode: 222, type: 'GIRLFRIEND', girlfriendNumber: 34 },
  { name: '中村 力斗', pronunciation: 'なかむら りきと', birthday: [5, 31], age: undefined, releasedLevel: 'ANIME', releaseSeason: 2, type: 'AUTHOR' },
  { name: '野澤 ゆき子', pronunciation: 'のざわ ゆきこ', birthday: [4, 17], age: undefined, releasedLevel: 'COMICS', releaseVolume: 9, type: 'AUTHOR' },
];
