export const IME_DICT_ITEM_CATEGORY = {
  TITLE: 'TITLE',
  CHARACTER_NAME_FULL: 'CHARACTER_NAME_FULL',
  CHARACTER_NAME_SHORT: 'CHARACTER_NAME_SHORT',
  CHARACTER_ANOTHERNAME_FULL: 'CHARACTER_ANOTHERNAME_FULL',
  CHARACTER_ANOTHERNAME_SHORT: 'CHARACTER_ANOTHERNAME_SHORT',
  CHARACTER_NICKNAME: 'CHARACTER_NICKNAME',
  CHARACTER_ANIME_VOICE_ACTOR: 'CHARACTER_ANIME_VOICE_ACTOR',
  LOCATION_NAME: 'LOCATION_NAME',
  LOCATION_NAME_ANOTHER: 'LOCATION_NAME_ANOTHER',
} as const;

export type ImeDictItemCategory = keyof typeof IME_DICT_ITEM_CATEGORY;

export interface ImeDictItem {
  reading: string;
  word: string;
  category: ImeDictItemCategory;
  comment: string | undefined;
}
